import Head from "next/head";
import { useRef } from "react";
import AboutMe from "../components/AboutMe/AboutMe";
import ContactMe from "../components/ContactMe/ContactMe";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import Hero from "../components/Hero/Hero";
import MySkills from "../components/MySkills/MySkills";
import MyWorks from "../components/MyWorks/MyWorks";
import SectionDivider from "../components/SectionDivider/SectionDivider";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const homeRef = useRef(null);
  const workRef = useRef(null);
  const skillRef = useRef(null);
  const aboutRef = useRef(null);
  const contactRef = useRef(null);

  const scrollHandler = (section) => {
    if (section === "home") {
      window.scrollTo({
        top: homeRef.current.offsetTop - 83,
        behavior: "smooth",
      });
    } else if (section === "work") {
      window.scrollTo({
        top: workRef.current.offsetTop - 83,
        behavior: "smooth",
      });
    } else if (section === "skill") {
      window.scrollTo({
        top: skillRef.current.offsetTop - 83,
        behavior: "smooth",
      });
    } else if (section === "about") {
      window.scrollTo({
        top: aboutRef.current.offsetTop - 83,
        behavior: "smooth",
      });
    } else if (section === "contact") {
      window.scrollTo({
        top: contactRef.current.offsetTop - 83,
        behavior: "smooth",
      });
    }
  };
  return (
    <>
      <Head>
        <title>Samuel Green</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/android-chrome-384x384.png" type="image/png" />
      </Head>

      <div className={styles.wrapper}>
        <Header scrollHandler={scrollHandler} />
        <main className={styles.main}>
          <Hero homeRef={homeRef} />
          <SectionDivider />
          <MyWorks workRef={workRef} />
          <SectionDivider />
          <MySkills skillRef={skillRef} />
          <SectionDivider />
          <AboutMe aboutRef={aboutRef} scrollHandler={scrollHandler} />
          <SectionDivider />
          <ContactMe contactRef={contactRef} />
        </main>
        <Footer scrollHandler={scrollHandler} />
      </div>
    </>
  );
}
